CREATE TABLE IF NOT EXISTS `user_subscriptions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_id` bigint unsigned DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `identifier` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `start_at` datetime DEFAULT NULL,
  `end_at` datetime DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `payment_id` bigint unsigned DEFAULT NULL,
  `plan_limitation` text DEFAULT NULL,
  `duration` text DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `plan_type` varchar(255) DEFAULT NULL,
  `module` varchar(32) DEFAULT NULL,
  `active_in_app_purchase_identifier` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_subscriptions_plan_id_foreign` (`plan_id`),
  KEY `user_subscriptions_user_id_index` (`user_id`),
  KEY `user_subscriptions_status_module_index` (`status`, `module`),
  CONSTRAINT `user_subscriptions_plan_id_foreign`
    FOREIGN KEY (`plan_id`) REFERENCES `user_plan` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
